version: '3.8'

services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile_php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini  # Montar php.ini
    networks:
      - laravel_network
    depends_on:
      - mysql
    command: >
      sh -c "
      chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
      php-fpm && php artisan migrate
      "

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  nginx:
    image: nginx:1.25
    container_name: laravel_nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9215:80"
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
